### ISSUE TITLE
Can you show the most recent log uploads per browser?

### ISSUE THREAD

**Issue by Satsank** [sppautomation/sppanalyzer#6]
This may have to be handled through a cookie because we need to limit it to a specific user where a user credential doesn't quite exist. In the home page, can we show the last 5 log keys or links so that I can toggle back to an earlier analysis as needed? 

Alternatively, if there is a way to send me an email with the link and some notes that I can type in, that will be useful as well.

**Comment by benjones917** [comment]
added cookie to hold last 5 log keys that were analyzed on that browser... display these as clickable links at bottom of upload page .... email alerts would take quite a bit more time to implement

**Comment by benjones917** [comment]
implemented cookie approach for now, can reopen if we need email alerts down the road
